### ISSUE TITLE
Can the environment configuration in foraging.yaml be modified?

### ISSUE THREAD

**Issue by issuey** [mansicer/MAIC#11]
When I change the configuration in foraging.yaml like this:
```
env_args:
  field_size: 20
  players: 10
  max_food: 6
  force_coop: False
  partially_observe: True
  sight: 3
  is_print: False
  need_render: False
```
There will be an error report about gym.error.UnregisteredEnv.
![image](https://github.com/mansicer/MAIC/assets/74280544/3c336a58-1fd0-4bd9-b4f7-5f5b73eaa923)
So I wonder whether the environment configuration in foraging.yaml can be modified?
Looking foward to your reply.Thank you very much.
